version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    expose:
      - "80"

  db:
    image: postgres:14
    restart: always
    environment:
        POSTGRES_PASSWORD: 'password'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'postgres'

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443