version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: 'lab02'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 80:80

  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'password'
        POSTGRES_USER: 'postgres'
        POSTGRES_DB: 'postgres'
